# Generated by Django 4.2.6 on 2023-11-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeplace", "0003_rename_cleanup_timeplace_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeplace",
            name="radius",
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
