# Generated by Django 4.2.7 on 2023-11-15 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timeplace", "0004_timeplace_radius"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeplace",
            old_name="user_id",
            new_name="user",
        ),
    ]
