# Generated by Django 4.2.7 on 2023-11-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeplace", "0007_prefill_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeplace",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
