# Generated by Django 4.2.7 on 2023-11-15 10:32

from django.db import migrations


def create_languages(apps, schema_editor):
    languages = [
        "Albanian",
        "العربية (Arabic)",
        "Հայերեն (Armenian)",
        "বাংলা (Bengali)",
        "Bosnian",
        "Bulgarian",
        "မြန်မာ (Burmese)",
        "中文 (Mandarin)",
        "Danish",
        "German",
        "English",
        "فارسی (Persian)",
        "Finnish",
        "French",
        "ქართული (Georgian)",
        "Ελληνικά (Greek)",
        "עִבְרִית (Hebrew)",
        "हिन्दी (Hindi)",
        "Italian",
        "Indonesian",
        "日本語 (Japanese)",
        "ខ្មែរ (Khmer)",
        "한국어 (Korean)",
        "Croatian",
        "ລາວ (Lao)",
        "मराठी (Marathi)",
        "Maltese",
        "Macedonian",
        "Dutch",
        "Norwegian",
        "Polish",
        "Portuguese",
        "ਪੰਜਾਬੀ (Punjabi)",
        "Romanian",
        "Русский (Russian)",
        "Swedish",
        "Serbian",
        "Slovak",
        "Slovenian",
        "Spanish",
        "Swahili",
        "Tagalog",
        "ไทย (Thai)",
        "Czech",
        "Turkish",
        "Hungarian",
        "اردو (Urdu)",
        "Tiếng Việt (Vietnamese)",

    ]
    Language = apps.get_model("user", "Language")
    for lang in languages:
        Language.objects.create(lang=lang)


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_email_alter_userlanguage_userprofile"),
    ]

    operations = [migrations.RunPython(create_languages)]
